#!/bin/bash

BRANCH=`git symbolic-ref --short HEAD`
SHA1=`git rev-parse HEAD`

function on_exit {
    git checkout master
}

trap on_exit EXIT

# we only care about commits on master.
if [ $BRANCH == "master" ] && grep -q "UPDATE" <(git log -1 --oneline); then
    make clean all # it is currently rebuilding everything
    git stash --all
    git checkout gh-pages
    git checkout stash -- .
    git checkout stash^3 -- .
    git stash drop
    git add -f *.html posts/*.html style.css
    git commit -m "built from $SHA1"
    git push
    git checkout master
fi